"""Add request_body_schema to Endpoint model

Revision ID: 93eecd814e97
Revises: 20240328224741
Create Date: 2025-03-31 14:36:46.631343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eecd814e97'
down_revision = '20240328224741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('request_body_schema', sa.JSON(), nullable=True))
    op.alter_column('headers', 'default_status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('url_parameters', 'default_status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_parameters', 'default_status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('headers', 'default_status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('endpoints', 'request_body_schema')
    # ### end Alembic commands ### 